RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
OLED_ENABLE = yes

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
TAP_DANCE_ENABLE = no
